### ISSUE TITLE
login接口本地调试没法正常调用

### ISSUE THREAD

**Issue by flazx** [hjkcai/cardiovascular-tracker#1]
http://localhost:3000/ch/api/login本地服务没法正常调用 

const app = new Koa()
app.use(LoggerMiddleware)
app.use(bodyParser())
app.use(rewrite(`/ch/*`, '/$1')) 
app.use(ApiResponserMiddleware)   
app.use(AuthMiddleware(/\/login$/))  -- 不处理login
app.use(router.prefix('/api').routes())  
看了逻辑，应当是用webchat这个router执行的，但是结果没有到这里router处理。

**Comment by hjkcai** [comment]
应该可以吧？有没有具体的报错内容呢？

**Comment by flazx** [comment]
仔细跟踪了一下发现，'login' 路径要改成 '/login'就可了，我的window下nodejs8.11.1版本。
-------------------------------------------------------------
router.post('/login', async (ctx, next) => { ... }

**Comment by hjkcai** [comment]
想起来了，我的早期代码都有这样的缺陷哈哈，在路由前面都加上 / 才正常。

这份代码目前不打算改了，因为目前小程序用的人太少。还是谢谢你的提醒！
